### ISSUE TITLE
没有错误提示的报错，PuLIDInsightFace加载器

### ISSUE THREAD

**Issue by yhhao-YH** [ZHO-ZHO-ZHO/ComfyUI-PuLID-ZHO#19]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\AKI\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AKI\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AKI\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AKI\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\AKI\ComfyUI-aki-v1.4\custom_nodes\PuLID_ComfyUI\pulid.py", line 240, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
  File "D:\AKI\ComfyUI-aki-v1.4\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

Prompt executed in 0.01 seconds
![image](https://github.com/user-attachments/assets/31395015-e69c-44e5-923b-cbdadc88c316)

**Comment by yhhao-YH** [comment]
我已经重新安装了insightface，下载了[clip-vit-large-patch14](https://hf-mirror.com/openai/clip-vit-large-patch14)，但是并没有效果
