### ISSUE TITLE
torchvision  0.18.0+cu121节点导入失败

### ISSUE THREAD

**Issue by vanch007** [ZHO-ZHO-ZHO/ComfyUI-PuLID-ZHO#3]
Traceback (most recent call last):
  File "D:\pinokio\api\comfyui\app\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\pinokio\api\comfyui\app\custom_nodes\ComfyUI-PuLID-ZHO\__init__.py", line 1, in <module>
    from . import PuLID
  File "D:\pinokio\api\comfyui\app\custom_nodes\ComfyUI-PuLID-ZHO\PuLID.py", line 9, in <module>
    from pulid.pipeline import PuLIDPipeline
  File "D:\pinokio\api\comfyui\app\custom_nodes\ComfyUI-PuLID-ZHO\pulid\pipeline.py", line 7, in <module>
    from basicsr.utils import img2tensor, tensor2img
  File "D:\pinokio\api\comfyui\app\env\lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "D:\pinokio\api\comfyui\app\env\lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "D:\pinokio\api\comfyui\app\env\lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "D:\pinokio\bin\miniconda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\pinokio\api\comfyui\app\env\lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "D:\pinokio\api\comfyui\app\env\lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

Cannot import D:\pinokio\api\comfyui\app\custom_nodes\ComfyUI-PuLID-ZHO module for custom nodes: No module named 'torchvision.transforms.functional_tensor'

**Comment by kft334** [comment]
I modifed the degradations.py file in the basicsr package and now it works.

Change from:
```
from torchvision.transforms.functional_tensor import rgb_to_grayscale
```

To:
```
from torchvision.transforms import functional as tf

def rgb_to_grayscale(image):

    return tf.to_grayscale(image, num_output_channels=1)
```

**Comment by curlysasha** [comment]
> degradations.py

same problem

**Comment by deepfree2023** [comment]
Change: 
from torchvision.transforms.functional_tensor import rgb_to_grayscale

To:

try:
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
except:
    from torchvision.transforms.functional import rgb_to_grayscale

**Comment by deepfree2023** [comment]
Modify the degradations.py file in the basicsr package.

Change:
`from torchvision.transforms.functional_tensor import rgb_to_grayscale`

To:
`
try:
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
except:
    from torchvision.transforms.functional import rgb_to_grayscale
`

**Comment by deepfree2023** [comment]
This maybe better.

Change:
```
from torchvision.transforms.functional_tensor import rgb_to_grayscale
```

To:
```
try: 
    from torchvision.transforms.functional_tensor import rgb_to_grayscale 
except: 
    from torchvision.transforms.functional import rgb_to_grayscale
```

**Comment by curlysasha** [comment]
not helped

> This maybe better.
> 
> Change:
> 
> ```
> from torchvision.transforms.functional_tensor import rgb_to_grayscale
> ```
> 
> To:
> 
> ```
> try: 
>     from torchvision.transforms.functional_tensor import rgb_to_grayscale 
> except: 
>     from torchvision.transforms.functional import rgb_to_grayscale
> ```
