### ISSUE TITLE
(IMPORT FAILED): C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO

### ISSUE THREAD

**Issue by freeexit2002** [ZHO-ZHO-ZHO/ComfyUI-PuLID-ZHO#4]
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1866, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\__init__.py", line 1, in <module>
    from . import PuLID
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\PuLID.py", line 9, in <module>
    from pulid.pipeline import PuLIDPipeline
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\pulid\pipeline.py", line 7, in <module>
    from basicsr.utils import img2tensor, tensor2img
ModuleNotFoundError: No module named 'basicsr'

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO module for custom nodes: No module named 'basicsr'

**Comment by alenhrp** [comment]
Missing basicsr dependency, just install it, pip intall basicsr.

**Comment by mr-bob-chang** [comment]
> Missing basicsr dependency, just install it, pip intall basicsr.

I have tried to install this dependency several times and get a message indicating that I have successfully installed it, but still can't import it

The full information is displayed below:

E:\ComfyUI_windows_portable-b>pip install basicsr
Requirement already satisfied: basicsr in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (1.4.2)
Requirement already satisfied: addict in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (2.4.0)
Requirement already satisfied: future in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (1.0.0)
Requirement already satisfied: lmdb in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (1.4.1)
Requirement already satisfied: numpy>=1.17 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (1.24.4)
Requirement already satisfied: opencv-python in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (4.8.0.74)
Requirement already satisfied: Pillow in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (10.2.0)
Requirement already satisfied: pyyaml in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (6.0.1)
Requirement already satisfied: requests in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (2.31.0)
Requirement already satisfied: scikit-image in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (0.20.0)
Requirement already satisfied: scipy in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (1.12.0)
Requirement already satisfied: tb-nightly in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (2.17.0a20240507)
Requirement already satisfied: torch>=1.7 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (2.3.0)
Requirement already satisfied: torchvision in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (0.18.0)
Requirement already satisfied: tqdm in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (4.65.0)
Requirement already satisfied: yapf in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from basicsr) (0.40.2)
Requirement already satisfied: filelock in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.7->basicsr) (3.12.2)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.7->basicsr) (4.10.0)
Requirement already satisfied: sympy in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.7->basicsr) (1.12)
Requirement already satisfied: networkx in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.7->basicsr) (3.1)
Requirement already satisfied: jinja2 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.7->basicsr) (3.1.2)
Requirement already satisfied: fsspec in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.7->basicsr) (2024.2.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.7->basicsr) (2021.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from requests->basicsr) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from requests->basicsr) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from requests->basicsr) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from requests->basicsr) (2023.7.22)
Requirement already satisfied: imageio>=2.4.1 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->basicsr) (2.31.3)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->basicsr) (2023.8.30)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->basicsr) (1.4.1)
Requirement already satisfied: packaging>=20.0 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->basicsr) (23.1)
Requirement already satisfied: lazy_loader>=0.1 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->basicsr) (0.3)
Requirement already satisfied: absl-py>=0.4 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from tb-nightly->basicsr) (2.1.0)
Requirement already satisfied: grpcio>=1.48.2 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from tb-nightly->basicsr) (1.63.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from tb-nightly->basicsr) (3.6)
Requirement already satisfied: protobuf!=4.24.0,<5.0.0,>=3.19.6 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from tb-nightly->basicsr) (4.25.3)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from tb-nightly->basicsr) (65.5.0)
Requirement already satisfied: six>1.9 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from tb-nightly->basicsr) (1.16.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from tb-nightly->basicsr) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from tb-nightly->basicsr) (3.0.3)
Requirement already satisfied: colorama in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from tqdm->basicsr) (0.4.6)
Requirement already satisfied: importlib-metadata>=6.6.0 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from yapf->basicsr) (6.8.0)
Requirement already satisfied: platformdirs>=3.5.1 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from yapf->basicsr) (3.9.1)
Requirement already satisfied: tomli>=2.0.1 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from yapf->basicsr) (2.0.1)
Requirement already satisfied: zipp>=0.5 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=6.6.0->yapf->basicsr) (3.16.2)
Requirement already satisfied: intel-openmp==2021.* in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.7->basicsr) (2021.4.0)
Requirement already satisfied: tbb==2021.* in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.7->basicsr) (2021.12.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from werkzeug>=1.0.1->tb-nightly->basicsr) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\hard_core\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch>=1.7->basicsr) (1.3.0)

Could it be because I installed the wrong directory? I tried it in the plugin directory, in the python directory, and in the ComfyUI_windows_portable directory, and I got the same result.

**Comment by zhizhurj** [comment]
[2025-05-17 22:08:11.058] Traceback (most recent call last):
  File "I:\ComfyUI_Mie_V4.0\ComfyUI\nodes.py", line 2131, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\ComfyUI_Mie_V4.0\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\__init__.py", line 7, in <module>
    from . import PuLID
  File "I:\ComfyUI_Mie_V4.0\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\PuLID.py", line 9, in <module>
    from pulid.pipeline import PuLIDPipeline
  File "I:\ComfyUI_Mie_V4.0\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\pulid\pipeline.py", line 7, in <module>
    from basicsr.utils import img2tensor, tensor2img
  File "I:\ComfyUI_Mie_V4.0\python_embeded\Lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "I:\ComfyUI_Mie_V4.0\python_embeded\Lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                       
I:\ComfyUI_Mie_V4.0\python_embeded>python -m pip show  basicsr
Name: basicsr
Version: 1.4.2
Summary: Open Source Image and Video Super-Resolution Toolbox
Home-page: https://github.com/xinntao/BasicSR
Author: Xintao Wang
Author-email: xintao.wang@outlook.com
License: Apache License 2.0
Location: I:\ComfyUI_Mie_V4.0\python_embeded\Lib\site-packages
Requires: addict, future, lmdb, numpy, opencv-python, Pillow, pyyaml, requests, scikit-image, scipy, tb-nightly, torch, torchvision, tqdm, yapf
Required-by:
