### ISSUE TITLE
install error with filterpy

### ISSUE THREAD

**Issue by curlysasha** [ZHO-ZHO-ZHO/ComfyUI-PuLID-ZHO#6]
`#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

## Execute install/(de)activation script for 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
 Collecting facexlib
   Downloading facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
 Collecting filterpy (from facexlib)
   Downloading filterpy-1.4.5.zip (177 kB)
      -------------------------------------- 178.0/178.0 kB 1.8 MB/s eta 0:00:00
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\user\AppData\Local\Temp\pip-install-e96p1554\filterpy_46a606a26f114bfe8a0c7a8554227df5\setup.py", line 4, in <module>
[!]       import filterpy
[!]   ModuleNotFoundError: No module named 'filterpy'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO

[ComfyUI-Manager] Startup script completed.
#######################################################################`

and then startup error

`Total VRAM 24563 MB, total RAM 65440 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
### ComfyUI Revision: 2128 [258dbc06] | Released on '2024-04-14'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\__init__.py", line 1, in <module>
    from . import PuLID
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\PuLID.py", line 9, in <module>
    from pulid.pipeline import PuLIDPipeline
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\pulid\pipeline.py", line 13, in <module>
    from facexlib.parsing import init_parsing_model
ModuleNotFoundError: No module named 'facexlib'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO module for custom nodes: No module named 'facexlib'`

**Comment by curlysasha** [comment]
Problem with filterpy


C:\ComfyUI_windows_portable\python_embeded>python.exe -m pip install facexlib
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting facexlib
  Downloading facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
Collecting filterpy (from facexlib)
  Downloading filterpy-1.4.5.zip (177 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.0/178.0 kB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-l53obyky\filterpy_f6bf5a731cbb47bca876cdda8d833291\setup.py", line 4, in <module>
          import filterpy
      ModuleNotFoundError: No module named 'filterpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ChrisAtJAM** [comment]
You need filterpy to install filterpy 🤷🏽‍♂️

See here:
https://github.com/cubiq/PuLID_ComfyUI/issues/1#issuecomment-2102591918

If that doesn't work Go here:
https://www.piwheels.org/project/filterpy/

Download [filterpy-1.4.5-py3-none-any.whl](https://www.piwheels.org/simple/filterpy/filterpy-1.4.5-py3-none-any.whl#sha256=227c2659b318061bb7ad5ec00f1b29ca3a8264f42b18c7be0d14487d521484d8):
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PuLID-ZHO/assets/81439381/8bc4768d-6920-49e4-8b65-e9536a2a901b)

Then wherever you downloaded that file do:
`C:\WhereverYouInstalledCOMFYUI\ComfyUI_windows_portable_nightly_pytorch\python_embeded\python.exe -m pip install .\filterpy-1.4.5-py3-none-any.whl`

Then you can install packages that use filterpy like facexlib:

`C:\WhereverYouInstalledCOMFYUI\ComfyUI_windows_portable_nightly_pytorch\python_embeded\python.exe -m pip install facexlib`

**Comment by curlysasha** [comment]
> You need filterpy to install filterpy 🤷🏽‍♂️
> 
> See here: [cubiq/PuLID_ComfyUI#1 (comment)](https://github.com/cubiq/PuLID_ComfyUI/issues/1#issuecomment-2102591918)
> 
> If that doesn't work Go here: https://www.piwheels.org/project/filterpy/
> 
> Download [filterpy-1.4.5-py3-none-any.whl](https://www.piwheels.org/simple/filterpy/filterpy-1.4.5-py3-none-any.whl#sha256=227c2659b318061bb7ad5ec00f1b29ca3a8264f42b18c7be0d14487d521484d8): ![image](https://private-user-images.githubusercontent.com/81439381/329288457-8bc4768d-6920-49e4-8b65-e9536a2a901b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzU3MjYsIm5iZiI6MTcxNTQzNTQyNiwicGF0aCI6Ii84MTQzOTM4MS8zMjkyODg0NTctOGJjNDc2OGQtNjkyMC00OWU0LThiNjUtZTk1MzZhMmE5MDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzNTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjM2JhYjUzNDYzYjgxMDg2NDNiNzdlZDY2ZTk5MDcxYzEyNWVmNjdmNTg4ZWEyMTYzZWUyM2I0YWEwNjI1MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rBMe_XOlTx1fRBC7OEBlRFRIa3hS4UmySIJX-Z6GiXs)
> 
> Then wherever you downloaded that file do: `C:\WhereverYouInstalledCOMFYUI\ComfyUI_windows_portable_nightly_pytorch\python_embeded\python.exe -m pip install .\filterpy-1.4.5-py3-none-any.whl`
> 
> Then you can install packages that use filterpy like facexlib:
> 
> `C:\WhereverYouInstalledCOMFYUI\ComfyUI_windows_portable_nightly_pytorch\python_embeded\python.exe -m pip install facexlib`

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\__init__.py", line 1, in <module>
    from . import PuLID
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\PuLID.py", line 9, in <module>
    from pulid.pipeline import PuLIDPipeline
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO\pulid\pipeline.py", line 7, in <module>
    from basicsr.utils import img2tensor, tensor2img
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO module for custom nodes: No module named 'torchvision.transforms.functional_tensor'

**Comment by talzahr** [comment]
>File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\degradations.py", line 8, in
from torchvision.transforms.functional_tensor import rgb_to_grayscale
> ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
> 
> Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-ZHO module for custom nodes: No module named 'torchvision.transforms.functional_tensor'

`functional_tensor` no longer exists. It's now simply `from torchvision.transforms.functional import rgb_to_grayscale` 

This is an issue with the release (stable) version of BasicSR.

You'll have to edit `C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\degradations.py`. Near the top of the file will be a line: `from torchvision.transforms.functional_tensor import rgb_to_grayscale`. Just remove the `_tensor` part. 

Alternative, someone packaged the fix for PyPi (pip) called [basicsr-fixed](https://pypi.org/project/basicsr-fixed/).
